#!/usr/bin/env node
// sigma-verify.mjs — Self-test orchestration for Sigma engine output.
// Companion to nava-sigma.mjs. Reads project + emits VERIFY-REPORT.md.
//
// Usage: node engine/sigma-verify.mjs <projectDir> [--port 3000] [--no-build]
//
// Pipeline:
//   1. Read SCAN-COVERAGE.md + COMPONENT-FIDELITY.md from <projectDir>
//   2. (optional) npm install + npm run build inside <projectDir>
//   3. Start "npm run dev" in background on --port (default 3000)
//   4. Poll /readiness via fetch until 200
//   5. Take screenshots: clone (localhost:port) + source (URL from
//      .data/scan.json) at 1920x1080
//   6. Walk all <section data-sigma-fidelity="..."> in clone DOM,
//      tally tier counts (high/medium/low) — runtime verification of
//      what engine reported pre-build
//   7. Emit VERIFY-REPORT.md combining all measurements
//
// Pixel-match measurement intentionally OPT-IN (not default) per
// feedback-sigma-cadence memory: capture coverage IS the metric, pixel
// match is bounded by font/image expression layer.

import fs from "node:fs";
import path from "node:path";
import { spawn, spawnSync } from "node:child_process";
import puppeteer from "puppeteer-core";

const CHROME = "C:/Program Files/Google/Chrome/Application/chrome.exe";
const args = process.argv.slice(2);
const projDir = path.resolve(args.find(a => !a.startsWith("--")) || "");
const portIdx = args.indexOf("--port");
const port = portIdx >= 0 ? parseInt(args[portIdx + 1], 10) : 3000;
const SKIP_BUILD = args.includes("--no-build");
const WITH_PIXELMATCH = args.includes("--pixelmatch");

if (!projDir || !fs.existsSync(projDir)) {
  console.error("usage: sigma-verify.mjs <projectDir> [--port 3000] [--no-build] [--pixelmatch]");
  process.exit(1);
}

const T0 = Date.now();
const el = () => ((Date.now() - T0) / 1000).toFixed(1) + "s";
console.log(`[sigma-verify] ${projDir} :${port}`);

// ─── Phase 1: Read existing artifacts ───
const scanJsonPath = path.join(projDir, ".data", "scan.json");
const coverageMd = path.join(projDir, "SCAN-COVERAGE.md");
const fidelityMd = path.join(projDir, "COMPONENT-FIDELITY.md");

if (!fs.existsSync(scanJsonPath)) {
  console.error("missing scan.json — was this directory generated by nava-sigma.mjs?");
  process.exit(1);
}
const scanData = JSON.parse(fs.readFileSync(scanJsonPath, "utf-8"));
const sourceUrl = scanData.url || scanData.title || "(unknown source)";
console.log(`  source: ${sourceUrl}`);

const coverageReport = fs.existsSync(coverageMd) ? fs.readFileSync(coverageMd, "utf-8") : "(no coverage report)";
const fidelityReport = fs.existsSync(fidelityMd) ? fs.readFileSync(fidelityMd, "utf-8") : "(no fidelity report)";

// ─── Phase 2: Build (optional) ───
if (!SKIP_BUILD) {
  console.log(`[Phase 2] build ${el()}`);
  if (!fs.existsSync(path.join(projDir, "node_modules"))) {
    console.log("  npm install...");
    const inst = spawnSync("npm", ["install"], { cwd: projDir, shell: true, stdio: "inherit" });
    if (inst.status !== 0) { console.error("npm install failed"); process.exit(1); }
  }
} else {
  console.log("  build skipped (--no-build)");
}

// ─── Phase 3: Start dev server ───
console.log(`[Phase 3] dev server ${el()}`);
const dev = spawn("npm", ["run", "dev", "--", "--port", String(port)], {
  cwd: projDir, shell: true, detached: false,
});
let serverReady = false;
dev.stdout?.on("data", (d) => {
  const t = d.toString();
  if (t.includes("Local:") || t.includes("ready")) serverReady = true;
});
dev.stderr?.on("data", (d) => { /* swallow */ });

// Poll readiness up to 60s
for (let i = 0; i < 60; i++) {
  await new Promise(r => setTimeout(r, 1000));
  if (serverReady) break;
  try {
    const res = await fetch(`http://localhost:${port}/`, { signal: AbortSignal.timeout(2000) });
    if (res.ok) { serverReady = true; break; }
  } catch { /* not ready */ }
}
if (!serverReady) {
  console.error("dev server did not start within 60s");
  dev.kill();
  process.exit(1);
}
console.log(`  ready on :${port}`);

// ─── Phase 4: Browser + screenshot capture ───
console.log(`[Phase 4] screenshots ${el()}`);
const browser = await puppeteer.launch({
  headless: "new", executablePath: CHROME,
  args: ["--no-sandbox", "--disable-dev-shm-usage"],
});
const page = await browser.newPage();
await page.setViewport({ width: 1920, height: 1080 });

const screenshotDir = path.join(projDir, ".verify");
fs.mkdirSync(screenshotDir, { recursive: true });

let runtimeFidelity = { high: 0, medium: 0, low: 0, total: 0 };
try {
  await page.goto(`http://localhost:${port}/`, { waitUntil: "networkidle2", timeout: 30000 });
  await new Promise(r => setTimeout(r, 2000));
  fs.writeFileSync(path.join(screenshotDir, "clone.png"), await page.screenshot({ fullPage: false }));
  // Walk runtime sections, tally fidelity tier
  runtimeFidelity = await page.evaluate(() => {
    const sections = [...document.querySelectorAll("section[data-sigma-fidelity]")];
    const out = { high: 0, medium: 0, low: 0, total: sections.length };
    for (const s of sections) {
      const tier = s.getAttribute("data-sigma-fidelity");
      if (tier === "high") out.high++;
      else if (tier === "medium") out.medium++;
      else out.low++;
    }
    return out;
  });
  console.log(`  clone runtime fidelity: high=${runtimeFidelity.high} med=${runtimeFidelity.medium} low=${runtimeFidelity.low} (${runtimeFidelity.total} sections)`);
} catch (e) { console.error(`  clone screenshot failed: ${e.message}`); }

let sourceShotOk = false;
if (sourceUrl.startsWith("http")) {
  try {
    await page.goto(sourceUrl, { waitUntil: "networkidle2", timeout: 30000 });
    await new Promise(r => setTimeout(r, 2000));
    fs.writeFileSync(path.join(screenshotDir, "source.png"), await page.screenshot({ fullPage: false }));
    sourceShotOk = true;
  } catch (e) { console.error(`  source screenshot failed: ${e.message}`); }
}

// ─── Phase 5: Optional pixelmatch ───
let pixelMatchPct = null;
if (WITH_PIXELMATCH && sourceShotOk) {
  try {
    const { default: pixelmatch } = await import("pixelmatch");
    const { PNG } = await import("pngjs");
    const a = PNG.sync.read(fs.readFileSync(path.join(screenshotDir, "clone.png")));
    const b = PNG.sync.read(fs.readFileSync(path.join(screenshotDir, "source.png")));
    const W = Math.min(a.width, b.width), H = Math.min(a.height, b.height);
    const ac = new PNG({ width: W, height: H }), bc = new PNG({ width: W, height: H });
    PNG.bitblt(a, ac, 0, 0, W, H, 0, 0);
    PNG.bitblt(b, bc, 0, 0, W, H, 0, 0);
    const diff = new PNG({ width: W, height: H });
    const mis = pixelmatch(ac.data, bc.data, diff.data, W, H, { threshold: 0.1, alpha: 0.3 });
    fs.writeFileSync(path.join(screenshotDir, "diff.png"), PNG.sync.write(diff));
    pixelMatchPct = ((1 - mis / (W * H)) * 100).toFixed(2);
    console.log(`  pixelmatch (opt-in): ${pixelMatchPct}%`);
  } catch (e) { console.error(`  pixelmatch failed: ${e.message}`); }
}

await browser.close();
dev.kill();

// ─── Phase 6: Emit VERIFY-REPORT.md ───
console.log(`[Phase 6] report ${el()}`);
const reportLines = [
  "# Sigma Verify Report",
  "",
  `Generated: ${new Date().toISOString()}`,
  `Source: ${sourceUrl}`,
  `Project: ${projDir}`,
  `Verify duration: ${el()}`,
  "",
  "## Runtime fidelity (post-build, served clone)",
  `- High: ${runtimeFidelity.high} sections`,
  `- Medium: ${runtimeFidelity.medium} sections`,
  `- Low: ${runtimeFidelity.low} sections`,
  `- Total: ${runtimeFidelity.total} sections`,
  "",
  pixelMatchPct ? `## Pixelmatch (--pixelmatch)\n- ${pixelMatchPct}% (clone vs source, viewport 1920x1080)\n` : "",
  "## Screenshot artifacts",
  `- \`.verify/clone.png\` — clone first viewport`,
  sourceShotOk ? `- \`.verify/source.png\` — source first viewport` : "",
  pixelMatchPct ? `- \`.verify/diff.png\` — pixelmatch diff visualization` : "",
  "",
  "## Notes",
  "- Capture coverage (NOT pixel-match) is the engine's true KPI",
  "  per feedback-sigma-cadence. Pixel-match opt-in only.",
  "- Runtime fidelity tier comes from `data-sigma-fidelity` HTML attr",
  "  (v86-3) embedded by engine into each emitted section.",
  "- See SCAN-COVERAGE.md + COMPONENT-FIDELITY.md for capture-side details.",
];
fs.writeFileSync(path.join(projDir, "VERIFY-REPORT.md"), reportLines.filter(Boolean).join("\n"));
console.log(`\n[done] ${el()} → VERIFY-REPORT.md`);
